#!/usr/bin/python3
"""
Handles app_views for Place class
"""
from api.v1.views.service_calls import *
from models.city import City
from models.place import Place

@view_route('/places_search', 'POST')
def search_places():
    '''
    retrieves places based on given json object
    '''
    # DESC:
    # json keys states, cities, amenties
    # if json invalid, return 400
    # if json (or every key) is empty return all places
    # caution: avoid duplicate items
    # filter by ALL amenities given
    #
    # LOGIC:
    # get all places
    # if states not empty
    #       for each state in states
    #           if place.state_id != state.id
    #               remove place from places

    pass


@view_route('/cities/<city_id>/places', 'POST')
def create_place(city_id):
    '''
    creates a new city object from the provided json
    if successful a json representation is returned
    '''
    return create_object_for(
        parent=City,
        child=Place,
        required=[
            'name',
            'user_id'
            'description'
            'number_rooms'
            'number_bathrooms'
            'max_guest'
            'price_by_night'
        ],
        parent_id={'city_id': city_id})


@view_route('/cities/<city_id>/places', 'GET')
def get_places(city_id):
    '''
    returns json list of all places found for a given state
    '''
    return get_all_objects_from(City, city_id, 'cities')


@view_route('/places/<place_id>', 'GET')
def get_place(place_id):
    '''
    returns json dict place found provided place_id
    if not such place exist 404 error is raised
    '''
    return get_single_object(place, place_id)


@view_route('/places/<place_id>', 'PUT')
def update_place(place_id):
    '''
    updates the place object found via the place_id
    if not such place exist 404 error is raised
    '''
    return update_object(place, place_id)


@view_route('/places/<place_id>', 'DELETE')
def delete_place(place_id):
    '''
    deletes the place object found via the place_id
    if not such place exist 404 error is raised
    '''
    return delete_object(place, place_id)
